### ISSUE TITLE
[ch13]Restart a stopped container and replace CMD

### ISSUE THREAD

**Issue by Kuanlin-Chen** [ayubiz/learn_docker_by_examples#1]
Are there any ways to start a stopped container and replace CMD ?

$ docker run -it -p 5901:5901 -e USER=root image
$ docker stop container
$ docker start -ai container

Warning: c2c3c923820a:1 is taken because of /tmp/.X1-lock
Remove this file if there is no X server c2c3c923820a:1
A VNC server is already running as :1

**Comment by ayubiz** [comment]
Hello,
It's impossible to restart a stopped container with a replacement of CMD, using 'docker commit' to export your stopped container as a new image file for a new start container which can have what CMD you want, it may the way that you can do. 

You can find out the details of the way mentioned above in the following url ...
https://stackoverflow.com/questions/32353055/how-to-start-a-stopped-docker-container-with-a-different-command
     
FYI ... ^^=

**Comment by Kuanlin-Chen** [comment]
Thanks!
